# Generated by Django 4.2 on 2024-10-01 23:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('envio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_de_carga', models.DateField()),
                ('peso_de_carga', models.DecimalField(decimal_places=2, max_digits=10)),
                ('titulo', models.CharField(max_length=255)),
                ('destino', models.CharField(max_length=255)),
                ('tipo_de_carga', models.CharField(max_length=100)),
                ('envio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='envio.envio', verbose_name='Envio')),
            ],
            options={
                'verbose_name_plural': 'Cargas',
            },
        ),
    ]
