# Generated by Django 4.2 on 2024-10-01 22:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('factura', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Envio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('fecha_envio', models.DateField()),
                ('codigo_carga', models.CharField(max_length=50)),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='factura.factura', verbose_name='Factura')),
            ],
            options={
                'verbose_name_plural': 'Envios',
            },
        ),
    ]
