# Generated by Django 4.2 on 2024-10-02 00:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ruta', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_de_vehiculo', models.CharField(max_length=100)),
                ('capacidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('consumo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ruta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ruta.ruta', verbose_name='Ruta')),
            ],
            options={
                'verbose_name_plural': 'Vehículos',
            },
        ),
    ]
