# Generated by Django 4.2 on 2024-10-01 23:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('carga', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('peso_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('carga', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='carga.carga', verbose_name='Carga')),
            ],
            options={
                'verbose_name_plural': 'Producto',
            },
        ),
    ]
