# Generated by Django 4.2 on 2024-10-04 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carga', '0001_initial'),
        ('producto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='carga',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='carga.carga', verbose_name='Carga'),
        ),
    ]
