# Generated by Django 4.2 on 2024-10-04 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proveedor', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proveedor',
            options={'verbose_name_plural': 'Proveedore'},
        ),
        migrations.RemoveField(
            model_name='proveedor',
            name='producto',
        ),
    ]
